---
apiVersion: v1
kind: Namespace
metadata:
  name: isd
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: innerspace-divers-web-deployment
  namespace: isd
spec:
  selector:
    matchLabels:
      app: innerspace-divers-web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: innerspace-divers-web-app
        version: "06980315a11c09bbd134c04ab477568108485f2b"
    spec:
      containers:
      - name: jekyll
        image: jekyll/jekyll:3.8
        command: ["/bin/sh"]
        args: ["-c", "bundle install --gemfile=/github/innerspacedivers/Gemfile; jekyll build -s /github/innerspacedivers -d /srv/jekyll; jekyll serve"]
        ports:
        - containerPort: 4000
        volumeMounts:
        - mountPath: /github
          name: git-isd-volume
      volumes:
      - name: git-isd-volume
        gitRepo:
          repository: "https://github.com/w3s7y/innerspacedivers.git"
          revision: "06980315a11c09bbd134c04ab477568108485f2b"

---
kind: Service
apiVersion: v1
metadata:
  name: innerspace-divers-web-service
  namespace: isd
spec:
  selector:
    app: innerspace-divers-web-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: innerspace-divers-web-ingress
  namespace: isd
spec:
  rules:
  - host: www.innerspacedivers.com
    http:
      paths:
      - path: /
        backend:
          serviceName: innerspace-divers-web-service
          servicePort: 80
