---
apiVersion: v1
kind: Namespace
metadata:
  name: hello-world
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: hello-world-html
  namespace: hello-world
data: 
  hello: |-
    <html><head>
    <title>Hello World</title>
    </head><body>
    <h1>Hello World</h1>
    </body></html>
  otherpage: |-
    <html><head><title>some other page</title></head>
    <body><h1>This is some other page<h1></body></html>
  config: |-
    server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world-app
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.10.0
        ports:
          - containerPort: 80
        volumeMounts:
          - name: hello-conf-vol
            mountPath: /usr/share/nginx/html
      volumes:
        - name: hello-conf-vol
          configMap:
            name: hello-world-html
            items:
              - key: hello
                path: hello.html
              - key: otherpage
                path: other.html

---
kind: Service
apiVersion: v1
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  selector:
    app: hello-world-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-ingress
  namespace: hello-world
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    #nginx.ingress.kubernetes.io/app-root: /
    kubernetes.io/ingress.class: ""
spec:
  rules:
  - host: k8s.westys.net
  - http:
      paths:
      - path: /
        backend:
          serviceName: hello-world-service
          servicePort: 80
